language: node_js
node_js:
  - "8"
  - "10"

cache:
  directories:
    - "node_modules"
    - "demo/node_modules"

install:
  - yarn install
  - yarn run lerna bootstrap

script:
  # Test Statusfy
  - yarn run lint
  - yarn run test

  # Test demo
  - cd packages/demo
  - yarn run build
  - yarn run generate
