language: node_js
node_js:
  - "8"
  - "10"

cache:
  directories:
    - "node_modules"
    - "demo/node_modules"

install:
  - yarn run install-dependencies

script:
  # Test Statusfy
  - yarn run lint
  - yarn run test

  # Test demo
  - yarn run demo:build
  - yarn run demo:generate
