language: node_js
node_js:
  - "8"
  - "10"

cache:
  directories:
    - "node_modules"
    - "demo/node_modules"

install:
  - npm install

script:
  # Test Statusfy
  - npm run lint && npm run lint:css
  - npm run test

  # Test demo
  - cd demo
  - npm add github:bazzite/statusfy#develop
  - npx statusfy generate
